# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sqsconsumerworker:
    image: sqsconsumerworker
    build:
      context: .
      dockerfile: SQS.Consumer.Worker/Dockerfile
    ports:
      - 5262:5262
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
